# Generated by Django 2.0.3 on 2018-04-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.IntegerField(default=1, verbose_name='test/config')),
                ('name', models.CharField(max_length=50, verbose_name='用例/配置名称')),
                ('belong_project', models.CharField(max_length=50, verbose_name='所属项目')),
                ('include', models.CharField(max_length=200, null=True, verbose_name='包含config/test')),
                ('author', models.CharField(max_length=20, verbose_name='编写人员')),
                ('request', models.TextField(verbose_name='请求信息')),
                ('status', models.IntegerField(default=1, verbose_name='有效/无效')),
            ],
            options={
                'db_table': 'CaseInfo',
                'verbose_name': '用例信息',
            },
        ),
        migrations.CreateModel(
            name='ModelsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('models_name', models.CharField(max_length=50, verbose_name='模块名称')),
                ('models_desc', models.CharField(max_length=500, verbose_name='模块概述')),
                ('status', models.IntegerField(default=1, verbose_name='有效/无效')),
                ('other_desc', models.CharField(max_length=100, null=True, verbose_name='其他信息')),
            ],
            options={
                'db_table': 'ModelsInfo',
                'verbose_name': '模块信息',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('responsible_name', models.CharField(max_length=20, verbose_name='负责人')),
                ('test_user', models.CharField(max_length=100, verbose_name='测试人员')),
                ('dev_user', models.CharField(max_length=100, verbose_name='开发人员')),
                ('publish_app', models.CharField(max_length=60, verbose_name='相关应用')),
                ('simple_desc', models.CharField(max_length=500, verbose_name='简要描述')),
                ('other_desc', models.CharField(max_length=100, null=True, verbose_name='其他信息')),
                ('status', models.IntegerField(default=1, verbose_name='有效/无效')),
            ],
            options={
                'db_table': 'ProjectInfo',
                'verbose_name': '项目信息',
            },
        ),
        migrations.AddField(
            model_name='modelsinfo',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MITTester.ProjectInfo'),
        ),
        migrations.AddField(
            model_name='caseinfo',
            name='belong_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MITTester.ModelsInfo'),
        ),
    ]
