# Generated by Django 2.0.3 on 2018-04-23 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MITTester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(max_length=50, verbose_name='状态配置')),
            ],
            options={
                'db_table': 'ConfigInfo',
                'verbose_name': '项目配置',
            },
        ),
        migrations.AlterField(
            model_name='modelsinfo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MITTester.ConfigInfo'),
        ),
    ]
